version: '3.7'

networks:
  ai-net:
      driver: bridge
services:
###############################################################
    nginx:
        hostname: nginx
        container_name: nginx
        build: ./images/nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
#        volumes:
#          - ./conf/hosts:/etc/nginx/conf.d
#          - ./conf/www:/var/www
#          - ./conf/logs:/var/log/nginx
#          - ./CA:/etc/ssl/
        networks:
          - ai-net
        privileged: true
###########################################################
    ultralitics_ai:
        hostname: ai
        container_name: ai
        build: ./images/ai
#        image: ultralytics/yolov5
#        command: nvidia-smi
#         ipc: host
        networks:
          - ai-net
#        deploy:
#           resources:
#             reservations:
#               devices:
#                 - capabilities: [gpu]
        logging:
          driver: "json-file"
          options:
            max-file: "3"
            max-size: 100m
        privileged: true
############################################################
